version: "3.8"

services:
    web:
        build: .
        ports:
            - "3000:3000"
        environment:
            - POSTGRES_USER=noteuser
            - POSTGRES_PASSWORD=notepassword
            - POSTGRES_DB=notedb
            - POSTGRES_HOST=db
            - POSTGRES_PORT=5432
            - PORT=3000
        depends_on:
            - db
        networks:
            - app-network
        volumes:
            - ./src:/usr/src/app:delegated
            - /usr/src/app/node_modules

    db:
        image: postgres:15-alpine
        restart: always
        environment:
            POSTGRES_USER: noteuser
            POSTGRES_PASSWORD: notepassword
            POSTGRES_DB: notedb
        volumes:
            - db-data:/var/lib/postgresql/data
            - ./src/init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - app-network

volumes:
    db-data:

networks:
    app-network:
